export type MockCustomer = {
  id: string;
  name: string;
  domain: string;
  industry: string;
  segment: "enterprise" | "mid_market" | "smb";
  arr: number;
  mrr: number;
  healthScore: number;
  healthStatus: "healthy" | "monitor" | "at_risk" | "critical";
  lifecycleStage: "onboarding" | "active" | "at_risk" | "churned";
  renewalDate: string;
  csmName: string;
  employeeCount: number;
  contractStart: string;
  churnProbability: number;
  riskLevel: "low" | "medium" | "high" | "critical";
  usageScore: number;
  revenueScore: number;
  supportScore: number;
  engagementScore: number;
  activeUsers: number;
  totalSeats: number;
  expansionScore: number;
  potentialExpansionArr: number;
  lastActivity: string;
  tags: string[];
};

export const mockCustomers: MockCustomer[] = [
  {
    id: "cust-001",
    name: "Apex Technologies",
    domain: "apextech.io",
    industry: "SaaS / Developer Tools",
    segment: "enterprise",
    arr: 180000,
    mrr: 15000,
    healthScore: 87,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-03-15",
    csmName: "Sarah Chen",
    employeeCount: 850,
    contractStart: "2023-03-15",
    churnProbability: 0.05,
    riskLevel: "low",
    usageScore: 90,
    revenueScore: 88,
    supportScore: 82,
    engagementScore: 88,
    activeUsers: 312,
    totalSeats: 350,
    expansionScore: 72,
    potentialExpansionArr: 48000,
    lastActivity: "2024-08-12",
    tags: ["power-user", "expansion-ready", "enterprise"],
  },
  {
    id: "cust-002",
    name: "Meridian Financial",
    domain: "meridianfin.com",
    industry: "FinTech",
    segment: "enterprise",
    arr: 240000,
    mrr: 20000,
    healthScore: 62,
    healthStatus: "monitor",
    lifecycleStage: "at_risk",
    renewalDate: "2024-11-30",
    csmName: "James Park",
    employeeCount: 1200,
    contractStart: "2022-11-30",
    churnProbability: 0.38,
    riskLevel: "high",
    usageScore: 58,
    revenueScore: 75,
    supportScore: 45,
    engagementScore: 70,
    activeUsers: 180,
    totalSeats: 400,
    expansionScore: 35,
    potentialExpansionArr: 24000,
    lastActivity: "2024-07-28",
    tags: ["renewal-risk", "low-adoption", "support-heavy"],
  },
  {
    id: "cust-003",
    name: "CloudNova Systems",
    domain: "cloudnova.dev",
    industry: "Cloud Infrastructure",
    segment: "mid_market",
    arr: 72000,
    mrr: 6000,
    healthScore: 91,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-07-01",
    csmName: "Maria Rodriguez",
    employeeCount: 220,
    contractStart: "2023-07-01",
    churnProbability: 0.03,
    riskLevel: "low",
    usageScore: 94,
    revenueScore: 90,
    supportScore: 95,
    engagementScore: 85,
    activeUsers: 98,
    totalSeats: 110,
    expansionScore: 85,
    potentialExpansionArr: 36000,
    lastActivity: "2024-08-14",
    tags: ["champion", "expansion-ready", "advocate"],
  },
  {
    id: "cust-004",
    name: "RetailPulse Inc",
    domain: "retailpulse.co",
    industry: "Retail Tech",
    segment: "mid_market",
    arr: 48000,
    mrr: 4000,
    healthScore: 34,
    healthStatus: "critical",
    lifecycleStage: "at_risk",
    renewalDate: "2024-09-15",
    csmName: "David Kim",
    employeeCount: 180,
    contractStart: "2023-09-15",
    churnProbability: 0.72,
    riskLevel: "critical",
    usageScore: 22,
    revenueScore: 40,
    supportScore: 28,
    engagementScore: 45,
    activeUsers: 12,
    totalSeats: 80,
    expansionScore: 5,
    potentialExpansionArr: 0,
    lastActivity: "2024-06-20",
    tags: ["churn-risk", "disengaged", "urgent"],
  },
  {
    id: "cust-005",
    name: "Nexus Analytics",
    domain: "nexusanalytics.ai",
    industry: "Data & Analytics",
    segment: "enterprise",
    arr: 156000,
    mrr: 13000,
    healthScore: 78,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-02-28",
    csmName: "Sarah Chen",
    employeeCount: 640,
    contractStart: "2023-02-28",
    churnProbability: 0.09,
    riskLevel: "low",
    usageScore: 82,
    revenueScore: 80,
    supportScore: 78,
    engagementScore: 72,
    activeUsers: 245,
    totalSeats: 280,
    expansionScore: 68,
    potentialExpansionArr: 36000,
    lastActivity: "2024-08-11",
    tags: ["stable", "upsell-candidate"],
  },
  {
    id: "cust-006",
    name: "GreenLeaf Logistics",
    domain: "greenleaf-log.com",
    industry: "Logistics & Supply Chain",
    segment: "mid_market",
    arr: 36000,
    mrr: 3000,
    healthScore: 55,
    healthStatus: "monitor",
    lifecycleStage: "active",
    renewalDate: "2024-12-01",
    csmName: "James Park",
    employeeCount: 320,
    contractStart: "2023-12-01",
    churnProbability: 0.28,
    riskLevel: "medium",
    usageScore: 52,
    revenueScore: 60,
    supportScore: 55,
    engagementScore: 53,
    activeUsers: 42,
    totalSeats: 70,
    expansionScore: 40,
    potentialExpansionArr: 12000,
    lastActivity: "2024-07-30",
    tags: ["monitor", "needs-qbr"],
  },
  {
    id: "cust-007",
    name: "Velocity Health",
    domain: "velocityhealth.io",
    industry: "HealthTech",
    segment: "smb",
    arr: 18000,
    mrr: 1500,
    healthScore: 96,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-06-30",
    csmName: "Maria Rodriguez",
    employeeCount: 55,
    contractStart: "2024-06-30",
    churnProbability: 0.02,
    riskLevel: "low",
    usageScore: 98,
    revenueScore: 95,
    supportScore: 97,
    engagementScore: 94,
    activeUsers: 32,
    totalSeats: 35,
    expansionScore: 78,
    potentialExpansionArr: 12000,
    lastActivity: "2024-08-14",
    tags: ["champion", "nps-promoter", "expansion-ready"],
  },
  {
    id: "cust-008",
    name: "DataBridge Corp",
    domain: "databridge.io",
    industry: "Data Integration",
    segment: "enterprise",
    arr: 120000,
    mrr: 10000,
    healthScore: 71,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-04-15",
    csmName: "David Kim",
    employeeCount: 480,
    contractStart: "2023-04-15",
    churnProbability: 0.14,
    riskLevel: "low",
    usageScore: 74,
    revenueScore: 72,
    supportScore: 70,
    engagementScore: 68,
    activeUsers: 192,
    totalSeats: 220,
    expansionScore: 55,
    potentialExpansionArr: 24000,
    lastActivity: "2024-08-08",
    tags: ["stable", "enterprise"],
  },
  {
    id: "cust-009",
    name: "SwiftPay Solutions",
    domain: "swiftpay.finance",
    industry: "Payment Processing",
    segment: "mid_market",
    arr: 54000,
    mrr: 4500,
    healthScore: 44,
    healthStatus: "at_risk",
    lifecycleStage: "at_risk",
    renewalDate: "2024-10-01",
    csmName: "Sarah Chen",
    employeeCount: 150,
    contractStart: "2023-10-01",
    churnProbability: 0.56,
    riskLevel: "high",
    usageScore: 38,
    revenueScore: 55,
    supportScore: 42,
    engagementScore: 40,
    activeUsers: 28,
    totalSeats: 90,
    expansionScore: 15,
    potentialExpansionArr: 0,
    lastActivity: "2024-07-01",
    tags: ["churn-risk", "intervention-needed", "renewal-in-60d"],
  },
  {
    id: "cust-010",
    name: "Horizon EdTech",
    domain: "horizonedtech.com",
    industry: "Education Technology",
    segment: "mid_market",
    arr: 42000,
    mrr: 3500,
    healthScore: 83,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-01-15",
    csmName: "Maria Rodriguez",
    employeeCount: 95,
    contractStart: "2024-01-15",
    churnProbability: 0.07,
    riskLevel: "low",
    usageScore: 86,
    revenueScore: 82,
    supportScore: 88,
    engagementScore: 76,
    activeUsers: 67,
    totalSeats: 80,
    expansionScore: 62,
    potentialExpansionArr: 18000,
    lastActivity: "2024-08-13",
    tags: ["growing", "upsell-candidate"],
  },
  {
    id: "cust-011",
    name: "TerraForm Labs",
    domain: "terraform-labs.io",
    industry: "Climate Tech",
    segment: "smb",
    arr: 24000,
    mrr: 2000,
    healthScore: 89,
    healthStatus: "healthy",
    lifecycleStage: "active",
    renewalDate: "2025-05-01",
    csmName: "James Park",
    employeeCount: 68,
    contractStart: "2024-05-01",
    churnProbability: 0.04,
    riskLevel: "low",
    usageScore: 91,
    revenueScore: 88,
    supportScore: 92,
    engagementScore: 85,
    activeUsers: 38,
    totalSeats: 40,
    expansionScore: 70,
    potentialExpansionArr: 12000,
    lastActivity: "2024-08-14",
    tags: ["healthy", "growing"],
  },
  {
    id: "cust-012",
    name: "Quantum Retail",
    domain: "quantumretail.com",
    industry: "Retail Analytics",
    segment: "enterprise",
    arr: 96000,
    mrr: 8000,
    healthScore: 38,
    healthStatus: "at_risk",
    lifecycleStage: "at_risk",
    renewalDate: "2024-10-30",
    csmName: "David Kim",
    employeeCount: 560,
    contractStart: "2022-10-30",
    churnProbability: 0.62,
    riskLevel: "critical",
    usageScore: 30,
    revenueScore: 50,
    supportScore: 35,
    engagementScore: 37,
    activeUsers: 45,
    totalSeats: 200,
    expansionScore: 8,
    potentialExpansionArr: 0,
    lastActivity: "2024-06-15",
    tags: ["churn-risk", "executive-escalation", "renewal-in-90d"],
  },
];

export function getCustomerById(id: string): MockCustomer | undefined {
  return mockCustomers.find((c) => c.id === id);
}

export function getCustomersByStatus(status: MockCustomer["healthStatus"]): MockCustomer[] {
  return mockCustomers.filter((c) => c.healthStatus === status);
}

export function getCustomersByRisk(risk: MockCustomer["riskLevel"]): MockCustomer[] {
  return mockCustomers.filter((c) => c.riskLevel === risk);
}

export const healthDistribution = {
  healthy: mockCustomers.filter((c) => c.healthStatus === "healthy").length,
  monitor: mockCustomers.filter((c) => c.healthStatus === "monitor").length,
  at_risk: mockCustomers.filter((c) => c.healthStatus === "at_risk").length,
  critical: mockCustomers.filter((c) => c.healthStatus === "critical").length,
};

export const totalARR = mockCustomers.reduce((sum, c) => sum + c.arr, 0);
export const totalMRR = mockCustomers.reduce((sum, c) => sum + c.mrr, 0);
